version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: moneychat-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: moneychat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # MinIO for file storage
  minio:
    image: minio/minio:latest
    container_name: moneychat-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # NLP Service (Python FastAPI)
  nlp-service:
    build: 
      context: ./nlp-service
      dockerfile: Dockerfile
    container_name: moneychat-nlp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./nlp-service:/app
    restart: unless-stopped

  # Backend API (NestJS)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: moneychat-backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - NLP_SERVICE_URL=http://nlp-service:8000
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
      - minio
      - nlp-service
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moneychat-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_WS_URL=ws://localhost:4000
      - GENERATE_SOURCEMAP=false
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data: