[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm install', 'npm run postinstall']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'