[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm install --production=false',
  'cd frontend && npm install'
]

[phases.build]
cmds = ['cd frontend && npm run build']

[phases.start]
cmd = 'cd frontend && npm start'

[variables]
NODE_ENV = 'production'